export const HEALTH_TEXT: string[] = [
  "Prioritize Your Wellness: A healthy life begins with small, consistent choices. Embrace daily exercise and nourishing meals to fuel your body's potential. Remember, every step you take today leads to a stronger, vibrant tomorrow.",
  'Energize Your Journey: Unleash your inner vitality through active living. Engage in activities that invigorate your senses and elevate your mood. Your body and mind are partners in this incredible adventure of health.',
  'Revitalize Your Being: Sleep, the cornerstone of well-being, rejuvenates your body and mind. Prioritize restful nights to awaken each day with renewed vigor. Your dreams deserve a well-rested canvas.',
  "Cherish Your Nutrition: Nourishment isn't just about what you eat—it's a celebration of life's flavors. Choose nutrient-rich options that sustain your vitality and foster a harmonious relationship with food.",
  'Empower Your Choices: Your health journey is a testament to your empowerment. With determination, you can overcome challenges and make positive strides towards a vibrant and fulfilling lifestyle.',
  'Thrive Through Connection: Cultivate your well-being within a community that supports and uplifts you. Shared goals and mutual encouragement create a space where health flourishes and friendships deepen.',
  "Age is Just a Number: Your body's potential knows no bounds. With each passing year, you have the opportunity to rewrite your story. Embrace the vitality that comes from caring for yourself.",
  "Mindfulness in Motion: Health is not just physical; it's a state of mind. Practice mindfulness to connect with your body's signals and engage with the present moment. Your journey is now.",
  'Strive for Progress, Not Perfection: Health is a journey, not a destination. Celebrate every step forward, regardless of its size. Embrace setbacks as opportunities to learn and grow.',
  'Radiate Positivity: A positive attitude is a powerful asset on your health journey. Your thoughts shape your actions; choose optimism, and let it illuminate the path to your well-being.',
  "Embrace Nature's Gym: The great outdoors offers a limitless playground for fitness. From hiking to biking, every adventure you embark upon is a step toward a healthier you.",
  "Hydration for Vibrancy: Water is life's elixir. Keep your body hydrated to support energy levels, digestion, and radiant skin. Sip your way to vitality throughout the day.",
  "Dance to Your Rhythm: Movement is joy in motion. Put on your favorite tunes and dance like nobody's watching. Let the rhythm elevate your heart and spirit.",
  'Mind-Body Harmony: Nurture your mental health as you do your physical well-being. Meditation, yoga, and deep breaths are pathways to inner balance and serenity.',
  'Celebrate Movement Diversity: Routine is the enemy of progress. Explore a variety of exercises to challenge your body and keep your fitness journey exciting.',
  'Cook with Love: Preparing meals is an act of self-care. Infuse your cooking with love and creativity, transforming food into a source of nourishment and pleasure.',
  'Posture for Power: Stand tall and proud; your posture reflects your self-assurance. A strong spine aligns with a strong mind. Elevate your presence through posture.',
  "Small Steps, Big Impact: Don't underestimate the power of incremental change. Small habits compound over time, leading to profound improvements in your well-being.",
  "Limitless Strength Within: Your body is a fortress of strength and resilience. Unearth your potential through challenges, knowing that you're capable of remarkable feats.",
  "Laugh Often, Live Well: Laughter is soul medicine. Find humor in life's moments, share joyful experiences, and let laughter be the soundtrack of your health journey.",
  "Prioritize Self-Care: You can't pour from an empty cup. Dedicate time to recharge and rejuvenate. Self-care isn't selfish; it's essential for your overall well-being.",
  'Chase Your Adventures: Health opens doors to new horizons. Climb mountains, explore new cities, and chase your wildest dreams fueled by the vitality of a life well-lived.',
  "Embrace Rest Days: Progress includes rest. Allow your body the time it needs to recover and rebuild, ensuring you're always ready to tackle the next challenge.",
  'Morning Momentum: Start your day with intention. Morning rituals set the tone for positive choices and accomplishments. Seize the dawn with enthusiasm and energy.',
  "Gratitude for Wellness: Cherish your body's capabilities with gratitude. Each heartbeat, each breath, is a gift. Treat your body kindly as it carries you through life.",
  'Unplug for Balance: Digital detoxes are a balm for the soul. Disconnect from screens to reconnect with nature, loved ones, and the simple pleasures around you.',
  "Discover Inner Warriors: Challenges reveal your inner strength. Just as a diamond is forged under pressure, you emerge stronger from life's trials. Embrace your inner warrior.",
  'Radiant from Within: Health radiates from your core. Cultivate self-love and acceptance, knowing that true beauty emanates from the confidence of a nurtured body and soul.',
  'Rise Strong After Falls: Setbacks are part of the journey. What matters is how you rise after a fall. Resilience defines your path to a healthier, happier you.',
  "Passion in Motion: Find a physical activity you're passionate about. When exercise becomes a joy, it's no longer a chore but a celebration of your body's capabilities.",
];
